sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
cors:
  originUrl:
    - 'http://192.168.110.72:8888'
    - 'http://192.168.110.72:8889'

